import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="Gates CSE Coding Tracker", layout="wide")

# Load the data generated by the ETL script
@st.cache_data
def load_data():
    try:
        return pd.read_csv("processed_scores.csv")
    except FileNotFoundError:
        st.error("Data not found. Please run etl_alerts.py first.")
        return pd.DataFrame()

df = load_data()

if not df.empty:
    st.title("📊 Gates CSE: Coding Progress Dashboard")
    
    # Top-level metrics
    col1, col2, col3 = st.columns(3)
    col1.metric("Total Students Tracked", len(df))
    col2.metric("Total Problems Solved", df['Total'].sum())
    col3.metric("At-Risk Students (<10 Solved)", len(df[df['Total'] < 10]))
    
    st.divider()
    
    # Visualizations and Tables
    left, right = st.columns([2, 1])
    
    with left:
        st.subheader("Global Leaderboard")
        # Sort by top performers
        leaderboard = df.sort_values(by="Total", ascending=False).reset_index(drop=True)
        st.dataframe(leaderboard[['Roll Number', 'Name', 'LeetCode', 'Total']], use_container_width=True)
        
    with right:
        st.subheader("Action Required: Low Scores")
        st.caption("These students have received automated email reminders.")
        # Filter strictly for low-performers so the observer knows exactly who is falling behind
        at_risk = df[df['Total'] < 10][['Roll Number', 'Name', 'Total']]
        st.dataframe(at_risk, use_container_width=True)

        